// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

type Query struct {
}

type Task struct {
	ID    int    `json:"id"`
	Title string `json:"title"`
	Done  bool   `json:"done"`
}
