version: "2"

linters:
  default: standard

formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    gofumpt:
      extra-rules: true
      module-path: github.com/alex-harvey-z3q/fullstack-golang-react-poc
    goimports:
      local-prefixes:
        - github.com/alex-harvey-z3q/fullstack-golang-react-poc

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
